### ISSUE TITLE
302 is maybe not the best status code?

### ISSUE THREAD

**Issue by kesla** [juliangruber/predirect#1]
hey,

> Many web browsers implemented this code in a manner that violated this standard, changing the request type of the new request to GET, regardless of the type employed in the original request (e.g. POST).

Above is taken from http://en.wikipedia.org/wiki/HTTP_302.

I always get super confused with the different 30X redirect codes so I don't really know what's best to use - but maybe 302 isn't the best status code for a convenience redirect module as this? Or maybe 302 is the best choice? I'm curious of your thinking!

**Comment by juliangruber** [comment]
302 is what express and koa use, so that was an obvious choice to me. 307 seems more fitting, however i'm not sure how well it is supported by browsers and tools like curl...
